# Generated by Django 4.2.8 on 2023-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_remove_items_items_group_idx_items_item_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
