# Generated by Django 4.2.8 on 2023-12-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_userorder_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockorder',
            options={'managed': True, 'ordering': ['-ordered_at']},
        ),
        migrations.AlterModelOptions(
            name='userorder',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
