# Generated by Django 4.2.8 on 2023-12-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_alter_items_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='order_number',
        ),
    ]
